# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "cl0", primary: true do |cl0|
    cl0.vm.box = "ubuntu/zesty64"
    cl0.vm.hostname = "CL0"
    cl0.vm.network "forwarded_port", guest: 22, host: 1033
    cl0.vm.network "private_network", ip: "192.168.33.10"
    #cl0.vm.network "public_network"
    # cl0.vm.synced_folder "./cl0", "/vagrant_data"
    # cl0.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
    # end
    cl0.ssh.username = "ubuntu"
    cl0.ssh.password = "221c36362c947c7882bd3db1"
    # cl0.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
    # SHELL
  end

  config.vm.define "cl1" do |cl1|
    cl1.vm.box = "ubuntu/zesty64"
    cl1.vm.hostname = "CL1"
    cl1.vm.network "forwarded_port", guest: 22, host: 1133
    cl1.vm.network "private_network", ip: "192.168.33.11"
    #cl1.vm.network "public_network"
    cl1.ssh.username = "ubuntu"
    cl1.ssh.password = "221c36362c947c7882bd3db1"
  end

  config.vm.define "cl2" do |cl2|
    cl2.vm.box = "ubuntu/zesty64"
    cl2.vm.hostname = "CL2"
    cl2.vm.network "forwarded_port", guest: 22, host: 1233
    cl2.vm.network "private_network", ip: "192.168.33.12"
    #cl2.vm.network "public_network"
    cl2.ssh.username = "ubuntu"
    cl2.ssh.password = "221c36362c947c7882bd3db1"
  end

  config.vm.define "cl3" do |cl3|
    cl3.vm.box = "ubuntu/zesty64"
    cl3.vm.hostname = "CL3"
    cl3.vm.network "forwarded_port", guest: 22, host: 1333
    cl3.vm.network "private_network", ip: "192.168.33.13"
    #cl3.vm.network "public_network"
    cl3.ssh.username = "ubuntu"
    cl3.ssh.password = "221c36362c947c7882bd3db1"
  end

end
